// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksLookup.Models;

namespace ParksLookup.Migrations
{
    [DbContext(typeof(ParksLookupContext))]
    partial class ParksLookupContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParksLookup.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Location")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Description = "Crater Lake inspires awe. Native Americans witnessed its formation 7,700 years ago, when a violent eruption triggered the collapse of a tall peak. Scientists marvel at its purity: fed by rain and snow, its the deepest lake in the USA and one of the most pristine on earth. Artists, photographers, and sightseers gaze in wonder at its blue water and stunning setting atop the Cascade Mountain Range.",
                            Location = "Crater Lake, OR",
                            Name = "Crater Lake",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 2,
                            Description = "From its thunderous ocean breakers crashing against rocky headlands and expansive sand beaches to its open grasslands, brushy hillsides, and forested ridges, Point Reyes offers visitors over 1500 species of plants and animals to discover. Home to several cultures over thousands of years, the Seashore preserves a tapestry of stories and interactions of people. Point Reyes awaits your exploration.",
                            Location = "Point Reyes, CA",
                            Name = "Point Reyes",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 3,
                            Description = "Follow the paths where native people and pioneers walked. Gaze up at massive sandstone cliffs of cream, pink, and red that soar into a brilliant blue sky. Experience wilderness in a narrow slot canyon. Zion’s unique array of plants and animals will enchant you as you absorb the rich history of the past and enjoy the excitement of present day adventures.",
                            Location = "Springdale, UT",
                            Name = "Zion",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 4,
                            Description = "In the southeast corner of Washington, Palouse Falls State Park is named after its iconic main attraction, the 198-foot Palouse Falls waterfall. While this scenic waterfall, often described as the best in the state, is the main attraction in the park, many visitors travel here for the chance to surround themselves with nature.",
                            Location = "LaCrosse, WA",
                            Name = "Palouse Falls",
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 5,
                            Description = "Formed of volcanic ash 30 million years ago and sculpted by wind and water into rows of monolithic blocks, City of Rocks State Park takes its name from these incredible rock formations. Cactus gardens and hiking trails add to this unique destination.",
                            Location = "Faywood, NM",
                            Name = "City of Rocks",
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 6,
                            Description = "Tonto Natural Bridge State Park is located in central Arizona near Payson. It is believed to be the largest natural travertine bridge in the world. The bridge stands 183 feet high over a 400-foot long tunnel that measures 150 feet at its widest point.",
                            Location = "Pine, AZ",
                            Name = "Tonto Natural Bridge",
                            Type = "State Park"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
